### ISSUE TITLE
What does U+FFFC character mean in CSS wiki page?

### ISSUE THREAD

**Issue by gundamew** [rocodev/guides#3]
What does U+FFFC character mean under title _block_ of chapter _Display types_ in [advanced css convention](https://github.com/rocodev/guides/wiki/advanced-css-convention) page?

**Comment by xdite** [comment]
可以請你說中文嗎？no offense

**Comment by hechien** [comment]
@xdite 我猜他想問的大概是「Stretch the full width of their container」是什麼意思吧

**Comment by gundamew** [comment]
@xdite 抱歉。我想問的是：在 advanced css convention 這一頁裡的 Display types 下，[block](https://github.com/rocodev/guides/wiki/advanced-css-convention#block) 第三點中的 ￼ 記號是什麼意思？[網誌的文章](http://blog.xdite.net/posts/2012/01/29/css-tricks-summary/)也有這個記號。
@hechien 不是

**Comment by xdite** [comment]
可能是亂碼 XDDDD

**Comment by gundamew** [comment]
@xdite 也就是說忽略它也不影響文意囉？

**Comment by xdite** [comment]
yes

**Comment by gundamew** [comment]
OK, thanks. :)

**Comment by gundamew** [comment]
一開始我是在 Firefox 上發現並提出這個問題，後來我用 Chrome 再次檢視這個 issue 時，我發現那個 [OBJECT REPLACEMENT CHARACTER](http://www.fileformat.info/info/unicode/char/fffc/index.htm) 消失了，這才了解為什麼大家看不懂我的問題，非常抱歉。orz

也讓我上了一課。
